FROM alpine:3.5
MAINTAINER Ralph-Gordon Paul <g.paul@appcom-interactive.de>

# set timezone to germany (Europe/Berlin)
RUN apk add --no-cache tzdata \
  && cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
  && apk del tzdata

# glibc is required for dynamic loading 
# https://github.com/sgerrand/alpine-pkg-glibc/releases
ENV GLIBC_FILE=glibc-2.25-r0.apk
ENV GLIBC_URI=https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.25-r0/glibc-2.25-r0.apk
RUN apk add --no-cache wget ca-certificates \
  && cd /tmp \
  && wget ${GLIBC_URI} \
  && apk --no-cache --allow-untrusted --force add ${GLIBC_FILE} \
  && apk del wget ca-certificates \
  && rm -rf /tmp/* /var/cache/apk/*

# set nodejs and npm version
ENV NODE_VERSION=v6.11.0
ENV NPM_VERSION=3

# install nodejs
RUN apk add --no-cache curl make gcc g++ python linux-headers binutils-gold gnupg libstdc++ \
  && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys \
     94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
     FD3A5288F042B6850C66B31F09FE44734EB7990E \
     71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
     DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
     C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
     B9AE9905FFD7803F25714661B63B535A4C206CA9 \
     56730D5401028683275BD23C23EFEFE93C4CFFFE \
  && curl -sSLO https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}.tar.xz \
  && curl -sSL https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt.asc | gpg --batch --decrypt | \
    grep " node-${NODE_VERSION}.tar.xz\$" | sha256sum -c | grep . \
  && tar -xf node-${NODE_VERSION}.tar.xz \
  && cd node-${NODE_VERSION} \
  && ./configure --prefix=/usr \
  && make -j$(getconf _NPROCESSORS_ONLN) \
  && make install \
  && cd / \
  && if [ -x /usr/bin/npm ]; then \
    npm install -g npm@${NPM_VERSION} \
    && find /usr/lib/node_modules/npm -name test -o -name .bin -type d | xargs rm -rf; \
  fi \
  && apk del curl make gcc g++ python linux-headers binutils-gold gnupg \
  && rm -rf /usr/include /node-${NODE_VERSION}* /usr/share/man /tmp/* /var/cache/apk/* /root/.npm /root/.node-gyp \
    /root/.gnupg /usr/lib/node_modules/npm/man /usr/lib/node_modules/npm/doc /usr/lib/node_modules/npm/html \
    /usr/lib/node_modules/npm/scripts

# port 3000 for http and 3001 for https
EXPOSE 3000 3001

# create the default nodejs app folder
RUN mkdir /node

# copy and set entrypoint
COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

# 'npm start' is the default command
CMD ["npm", "start"]
