FROM debian:stretch-20180426
MAINTAINER Ralph-Gordon Paul <g.paul@appcom-interactive.de>

# set timezone to germany
RUN ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

# install nodejs and yarn
RUN apt-get update --no-install-recommends \
  && apt-get install -y curl --no-install-recommends \
  && curl -sL https://deb.nodesource.com/setup_9.x | /bin/bash - \
  && apt-get update --no-install-recommends \
  && apt-get install -y nodejs \
  # some packages may require the developer build tools
  && apt-get install -y build-essential \
  && apt-get purge -y --auto-remove curl \
  && rm -rf /var/lib/apt/lists/*

# port 3000 for http and 3001 for https
EXPOSE 3000 3001

# create the default nodejs app folder
RUN mkdir /node

# copy and set entrypoint
COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

# 'npm start' is the default command
CMD ["npm", "start"]
